namespace MiniMockito.Shims.Experimental;

/// <summary>
/// Entry point called from wrapper methods generated by <c>StaticCallRewriter</c>.
/// Matches the call against registered static shim rules and executes the matching rule.
/// </summary>
/// <remarks>
/// <b>Experimental.</b> This class is generated into rewritten assemblies by the build-time weaver.
/// <para>
/// Dispatch diagnostics are recorded in <see cref="ShimContext.LastStaticDispatchDiagnostics"/>
/// after every call within an active <see cref="ShimContext"/>.
/// </para>
/// <para>
/// The rule key is string-based (<see cref="StaticMethodKey"/>), so there is no type identity
/// problem across isolated <see cref="System.Runtime.Loader.AssemblyLoadContext"/> boundaries.
/// </para>
/// </remarks>
public static class StaticShimDispatcher
{
    /// <summary>
    /// Attempts to match a registered rule and return the shimmed value.
    /// Returns <see langword="true"/> if a rule was found and executed;
    /// <see langword="false"/> means the wrapper should fall back to the real method.
    /// </summary>
    /// <typeparam name="TResult">The return type of the shimmed static method.</typeparam>
    /// <param name="declaringTypeFullName">Full name of the declaring type.</param>
    /// <param name="methodName">Method name.</param>
    /// <param name="parameterTypes">Parameter types in declaration order.</param>
    /// <param name="args">Boxed actual arguments in declaration order.</param>
    /// <param name="result">Receives the shimmed return value when a rule is found.</param>
    public static bool TryInvoke<TResult>(
        string declaringTypeFullName,
        string methodName,
        Type[] parameterTypes,
        object?[] args,
        out TResult result)
    {
        var key = new StaticMethodKey(
            declaringTypeFullName,
            methodName,
            parameterTypes.Select(t => t.FullName ?? t.Name).ToArray());

        var context = ShimContext.Current;
        if (context is { IsDisposed: false })
        {
            if (context.StaticRegistry.TryFindRuleWithDiagnostics(key, args, out var rule, out var diag))
            {
                context.LastStaticDispatchDiagnostics = diag;
                rule!.TryExecute(args, out var rawResult);
                result = rawResult is null ? default! : (TResult)rawResult;
                return true;
            }

            context.LastStaticDispatchDiagnostics = diag;
        }

        result = default!;
        return false;
    }

    /// <summary>
    /// Attempts to match a registered rule for a void static method.
    /// Returns <see langword="true"/> if a rule was found and executed;
    /// <see langword="false"/> means the wrapper should fall back to the real method.
    /// </summary>
    public static bool TryInvokeVoid(
        string declaringTypeFullName,
        string methodName,
        Type[] parameterTypes,
        object?[] args)
    {
        var key = new StaticMethodKey(
            declaringTypeFullName,
            methodName,
            parameterTypes.Select(t => t.FullName ?? t.Name).ToArray());

        var context = ShimContext.Current;
        if (context is { IsDisposed: false })
        {
            if (context.StaticRegistry.TryFindRuleWithDiagnostics(key, args, out var rule, out var diag))
            {
                context.LastStaticDispatchDiagnostics = diag;
                rule!.TryExecute(args, out _);
                return true;
            }

            context.LastStaticDispatchDiagnostics = diag;
        }

        return false;
    }
}
